name: SoloLevelingUHC
version: 0.1
description: Un plugin UHC sur le theme de l'oeuvre Solo Leveling.
main: fr.SoloLeveling.uhc.Main
author: Qomoxyy l3mon_ice
commands:
  sl:
    description: Permet d'accéder à toutes les commandes du mode de jeu UHC Solo Leveling.
    permission: admin
    permission-message: §4[SL] Vous n'avez pas les permission pour utiliser cette commande.
  sl color:
    description: Permet de mettre en couleur les joueurs de la partie.
    permission: None
    permission-message: None

  say:
    description: Envoie une alerte(broadcast)
    permission: admin
    permission-message: §4[SL] Vous n'avez pas les permission pour utiliser cette commande.
  mb:
    description: Envoie les informations du mumble de la game associée.
    alias: mb, mumble, mmb
    permission: admin
    permission-message: None
  start:
    description: Permet de lancer la partie.
    permission: admin
    permission-message: §4[SL] Vous n'avez pas les permission pour utiliser cette commande.