name: SoloLevelingUHC
version: 0.1
description: Un plugin UHC sur le theme de l'oeuvre Solo Leveling.
main: fr.SoloLeveling.uhc.Main
author: Qomoxyy l3imonice
commands:
  sl:
    description: Permet d'acceder ร toutes les commande du mode de jeu UHC Solo Leveling.
    permission: admin
    permission-message: ยง4[SL] Vous n'avez pas les permission pour utiliser cette commande.
  sl color:
    description: Permet de mettre en couleur les joueurs de la partie.
    permission: None
    permission-message: None

  say:
    description: Envoie une alerte(broadcast)
    permission: admin
    permission-message: ยง4[SL] Vous n'avez pas les permission pour utiliser cette commande.
